ruby '2.3.1'

source 'https://rubygems.org'

gem 'roda', '2.16.0'
gem 'rack-unreloader', '1.5.0'
gem 'thin', '1.7.0'
gem 'opal', '0.10.1'
gem 'akin', path: '..'
gem 'sass', '3.4.22'

group :test, :development do
  gem 'pry', '0.10.4'
  gem 'awesome_print', '1.7.0'
end

group :test do
  gem 'rspec', '3.5.0'
  gem 'opal-rspec', '0.6.0.beta1'
end

source 'https://rails-assets.org' do
  gem 'rails-assets-jquery', '3.1.0'
  gem 'rails-assets-todomvc-common', '1.0.2'
  gem 'rails-assets-todomvc-app-css', '2.0.6'
end
